PoolFootballApp/config/routes.rb
Rails.application.routes.draw do
  # For now we disable the resources routes, to be re-activated for admin side
  # resources :users
  # resources :picks
  # resources :poolers
  # resources :pools
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Sessions base routes to login and logout
  get '/' => 'sessions#login'
  get '/sessions/goodbye' => 'sessions#goodbye'

  # Auth results routing
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get 'auth/failure' => '/'

  # Client facing resources
  resources :pools, only: [:index]
  resources :poolers, only: [:index, :new, :create, :show, :edit, :update]

  get '/picks' => 'picks#index'

  get '/picks/new/:season/:week' => 'picks#new', as: :new_pick_path
  post '/picks' => 'picks#create'

  get '/picks/:id' => 'picks#show', as: :pick
  get '/picks/search/:season/:week' => 'picks#show_week', as: :search_pick
end

PoolFootballApp/app/models/pool.rb
class Pool
  include Mongoid::Document
  field :name, type: String
  field :motp, type: String

  has_many :poolers, dependent: :destroy
end

PoolFootballApp/app/controllers/pools_controller.rb
# Class to handle all process to Pools data
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools
  # GET /pools.json
  def index
    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end

    @pool = Pooler.where(user_id: user.id).first.pool
    @poolers = @pool.poolers.to_a

    if !params[:season].nil? && !params[:week].nil?
      @week_info = {
        season: params[:season],
        week: params[:week]
      }
    else
      @week_info = find_current_week(@poolers)
    end

    if params[:season_total].nil?
      @week_data = get_week(@week_info[:season].to_s, @week_info[:week].to_s)['events'].map do |x|
        x[:home_code] = get_shortname(x['strHomeTeam'])
        x[:home_won] = x['intHomeScore'].to_i > x['intAwayScore'].to_i

        x[:away_code] = get_shortname(x['strAwayTeam'])
        x[:away_won] = x['intAwayScore'].to_i > x['intHomeScore'].to_i
        x
      end
      picks_data = @poolers.map do |pooler|
        {
          p: pooler,
          picks: pooler.picks.where(season: @week_info[:season], week: @week_info[:week]).first
        }
      end

      @results = calculate_week_results(picks_data, @week_data, @week_info[:week])
      @totals = @results.map do |r|
        r.reduce(0) { |t, c| t = t + c }
      end
    else
      @results = (1..@week_info[:week]).map do |w|
        week_data = get_week(@week_info[:season].to_s, w.to_s)['events'].map do |x|
          x[:home_code] = get_shortname(x['strHomeTeam'])
          x[:home_won] = x['intHomeScore'].to_i > x['intAwayScore'].to_i

          x[:away_code] = get_shortname(x['strAwayTeam'])
          x[:away_won] = x['intAwayScore'].to_i > x['intHomeScore'].to_i
          x
        end
        picks_data = @poolers.map do |pooler|
          {
            p: pooler,
            picks: pooler.picks.where(season: @week_info[:season], week: w).first
          }
        end

        calculate_week_results(picks_data, week_data, w).map do |r|
          r.reduce(0) do |t, c|
            t = c >= 0 ? t + c : t + 0
          end
        end
      end

      @totals = @poolers.each_with_index.map do |_, i|
        @results.reduce(0) do |t, a|
          t = t + a[i]
        end
      end
    end
  end

  # GET /pools/1
  # GET /pools/1.json
  def show
    puts '[Pools][Show]'
  end

  # GET /pools/new
  def new
    @pool = Pool.new
  end

  # GET /pools/1/edit
  def edit
    puts '[Pools][Edit]'
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)

    respond_to do |format|
      if @pool.save
        format.html { redirect_to @pool, notice: 'Pool was successfully created.' }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: 'Pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { render :edit }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to pools_url, notice: 'Pool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pool
    @pool = Pool.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pool_params
    params.require(:pool).permit(:name, :motp)
  end

    def find_current_week(poolers)
      t = poolers.reduce({ season: -1, week: -1 }) do |maxes, pooler|
        max_season = pooler.picks.max_by { |p| p.season }

        if !max_season.nil? && max_season.season > maxes[:season]
          maxes[:season] = max_season.season
          maxes[:week] = pooler.picks.where(season: max_season.season).max_by { |p| p.week }.week
        end

        maxes
      end

      t[:season] = Date.today.year if t[:season] == -1
      t[:week] = 1 if t[:week] == -1

      t
    end

    def calculate_week_results(picks_data, week_data, week)
      picks_data.map do |e|
        if e[:picks].nil?
          (0...week_data.size).map { |_| -1 }
        else
          picks = e[:picks].parse_picks
          week_data.each_with_index.map do |game, i|
            curr_pick = e[:picks].json_picks? ? picks[game['idEvent']] : picks[i]

            if (game[:away_won] && curr_pick == game[:away_code]) ||
               (game[:home_won] && curr_pick == game[:home_code])

              # pooler was right
              unique = picks_data.one? do |x|
                if !x[:picks].nil?
                  x_picks = x[:picks].parse_picks
                  other_current = x[:picks].json_picks? ? x_picks[game['idEvent']] : x_picks[i]
                  other_current == curr_pick
                else
                  false
                end
              end

              correctScore = get_correct_score(week)
              unique ? (1.5*correctScore).to_i : correctScore
            else
              # pooler was wrong OR tie game OR no score
              tied = (!game[:away_won] && !game[:home_won] &&
                      !game['intAwayScore'].nil? && !game['intHomeScore'].nil?)

              tied ? 1 : 0
            end
          end
        end
      end
    end

  def get_correct_score(week)
    n = week
    n = n.to_i if n.is_a? String

    return 2 if n < 19
    return 4 if n == 19
    return 6 if n == 20
    return 8 if n == 21
    return 10 if n == 22
  end
end

PoolFootballApp/app/helpers/pools_helper.rb
module PoolsHelper
end

PoolFootballApp/app/views/pools/_form.html.erb
<%= form_with(model: pool, local: true) do |form| %>
  <% if pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
        <% pool.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :motp %>
    <%= form.text_field :motp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

PoolFootballApp/app/views/pools/edit.html.erb
<h1>Editing Pool</h1>

<%= render 'form', pool: @pool %>

<%= link_to 'Voir', @pool %> |
<%= link_to 'Retour', pools_path %>

PoolFootballApp/app/views/pools/index.html.erb
<p id="notice"><%= notice %></p>

<h4>
  Pour saison <%= @week_info[:season] %>
  <% if (params[:season_total] == nil) then %>
    - <%= get_week_long_name(@week_info[:week]) %>
  <% end %>
</h4>

<% if (params[:season_total] == nil) then %>

<table class="table table-sm table-bordered">
  <thead>
    <tr>
      <th colspan="7">Match</th>
      <% @poolers.each do |p| %>
        <th style="text-align: center"><%= p.name %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @week_data.each_with_index do |game, gi| %>
    <tr>
      <td><%= game["strAwayTeam"] %></td>
      <td style="text-align: center"><%= image_tag("#{game[:away_code]}.png", size: "21") %></td>
      <% if (game[:away_won]) %>
        <td>(<strong><%= game["intAwayScore"] %></strong>)</td>
      <% else %>
        <td>(<%= game["intAwayScore"] %>)</td>
      <% end %>
      <td>VS.</td>
      <% if (game[:home_won]) %>
        <td>(<strong><%= game["intHomeScore"] %></strong>)</td>
      <% else %>
        <td>(<%= game["intHomeScore"] %>)</td>
      <% end %>
      <td style="text-align: center"><%= image_tag("#{game[:home_code]}.png", size: "21") %></td>
      <td style="text-align: right"><%= game["strHomeTeam"] %></td>

      <% (0...@poolers.size).each do |pi| %>
        <% if (pi == 0) %>
          <td style="text-align: center; border-left: 2px solid #000">
            <%= @results[pi][gi] >= 0 ? "+#{@results[pi][gi]}" : '-' %>
          </td>
        <% else %>
          <td style="text-align: center">
            <%= @results[pi][gi] >= 0 ? "+#{@results[pi][gi]}" : '-' %>
          </td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  <tr>
    <th colspan="7" style="text-align: center; border-top: 2px solid #000">Total -></th>
    <% @totals.each do |t| %>
      <th style="text-align: center; border-top: 2px solid #000">
        <%= (t >= 0) ? t : '-' %>
      </th>
    <% end %>
  </tr>
  </tbody>
</table>

Autres semaines
<div class="btn-group" role="group">
  <% (1..22).each do |w| %>
    <% if (w == @week_info[:week].to_i) then %>
      <a href="#"
        class="btn btn-outline-secondary btn-sm disabled"
        role="button">
          <small><%= get_week_name(w) %></small>
      </a>
    <% else %>
      <a href="<%= url_for pools_path(season: @week_info[:season], week: w) %>"
        class="btn btn-primary btn-sm"
        role="button">
          <small><%= get_week_name(w) %></small>
      </a>
    <% end %>
  <% end %>
</div>

<div>
  Total de la saison
  <a href="<%= url_for pools_path(season: @week_info[:season], season_total: true) %>"
    class="btn btn-primary btn-sm"
    role="button">
      <small><%= @week_info[:season] %></small>
  </a>
</div>

<% else %>

<table class="table table-sm table-bordered">
  <tr>
    <th>Semaines</th>
    <% @poolers.each do |pooler| %>
      <th><%= pooler.name %></th>
    <% end %>
  </tr>
  <% @results.each_with_index do |result, i| %>
    <tr>
      <td><%= get_week_long_name(i+1) %></td>
      <% result.each do |score| %>
        <td><%= score %></td>
      <% end %>
    </tr>
  <% end %>
  <tr>
    <th>Total</th>
    <% @totals.each do |t| %>
      <th><%= t %></th>
    <% end %>
  </tr>
</table>

<div>
  <%= link_to "Retour", pools_path %>
</div>

<% end %>

<p>Pool: <%= @pool.name %> - <i>"<%= @pool.motp %>"</i></p>

PoolFootballApp/app/views/pools/new.html.erb
<h1>New Pool</h1>

<%= render 'form', pool: @pool %>

<%= link_to 'Retour', pools_path %>

PoolFootballApp/app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pool.name %>
</p>

<p>
  <strong>Motp:</strong>
  <%= @pool.motp %>
</p>

<%= render @pool.poolers %>

<%= link_to 'Modifier', edit_pool_path(@pool) %> |
<%= link_to 'Retour', pools_path %>