PoolFootballApp/config/routes.rb
Rails.application.routes.draw do
  # For now we disable the resources routes, to be re-activated for admin side
  # resources :users
  # resources :picks
  # resources :poolers
  # resources :pools
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Sessions base routes to login and logout
  get '/' => 'sessions#login'
  get '/sessions/goodbye' => 'sessions#goodbye'

  # Auth results routing
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get 'auth/failure' => '/'

  # Client facing resources
  resources :pools, only: [:index]
  resources :poolers, only: [:index, :new, :create, :show, :edit, :update]

  get '/picks' => 'picks#index'

  get '/picks/new/:season/:week' => 'picks#new', as: :new_pick_path
  post '/picks' => 'picks#create'

  get '/picks/:id' => 'picks#show', as: :pick
  get '/picks/search/:season/:week' => 'picks#show_week', as: :search_pick
end

PoolFootballApp/app/models/pooler.rb
class Pooler
  include Mongoid::Document
  field :name, type: String
  field :favTeam, type: String

  belongs_to :pool, optional: true
  belongs_to :user

  has_many :picks, class_name: Pick
end

PoolFootballApp/app/controllers/poolers_controller.rb
# Class to handle all process to Poolers data
class PoolersController < ApplicationController
  before_action :set_pooler, only: [:show, :edit, :update, :destroy]

  # GET /poolers
  # GET /poolers.json
  def index
    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end

    pooler = Pooler.where(user_id: user.id).first
    redirect_to pooler
  end

  # GET /poolers/1
  # GET /poolers/1.json
  def show
    @pool = Pool.where(id: @pooler.pool_id).first
  end

  # GET /poolers/new
  def new
    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end

    @pooler = Pooler.where(user_id: user.id).first
    if !@pooler.nil?
      redirect_to @pooler
      return
    end

    @pooler = Pooler.new
    @teams = get_teams
  end

  # GET /poolers/1/edit
  def edit
    @teams = get_teams
  end

  # POST /poolers
  # POST /poolers.json
  def create
    @pooler = Pooler.new(pooler_params)

    @user = User.where(token: session[:user_token]).first
    if @user.nil?
      redirect_to '/'
      return
    end

    @pooler.pool_id = BSON::ObjectId.new
    @pooler.user_id = @user.id

    respond_to do |format|
      if @pooler.save
        format.html { redirect_to @pooler, notice: 'Pooler was successfully created.' }
        format.json { render :show, status: :created, location: @pooler }
      else
        format.html { render :new }
        format.json { render json: @pooler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poolers/1
  # PATCH/PUT /poolers/1.json
  def update
    respond_to do |format|
      if @pooler.update(pooler_params)
        format.html { redirect_to @pooler, notice: 'Pooler was successfully updated.' }
        format.json { render :show, status: :ok, location: @pooler }
      else
        format.html { render :edit }
        format.json { render json: @pooler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poolers/1
  # DELETE /poolers/1.json
  # def destroy
  #  @pooler.destroy
  #  respond_to do |format|
  #    format.html { redirect_to poolers_url, notice: 'Pooler was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pooler
    @pooler = Pooler.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pooler_params
    params.require(:pooler).permit(:name, :favTeam)
  end
end

PoolFootballApp/app/helpers/poolers_helper.rb
module PoolersHelper
end

PoolFootballApp/app/views/poolers/_form.html.erb
<script>
  function setFavTeam(favTeam, imgSrc)
  {
    var favTeamHidden = document.getElementById("pooler_favTeam");
    favTeamHidden.value = favTeam;

    var currentTeam = document.getElementById("currentTeamName");
    currentTeam.innerHTML = favTeam;

    var currentImg = document.getElementById("currentTeamImg");
    currentImg.src = imgSrc;
  }
</script>

<%= form_with(model: pooler, local: true) do |form| %>
  <% if pooler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pooler.errors.count, "error") %> prohibited this pooler from being saved:</h2>

      <ul>
        <% pooler.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="dropdown">
    <button class="btn-sm btn-secondary dropdown-toggle"
            type="button"
            id="dropdownMenu2"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
            data-display="static">
      <%= image_tag("ARI.png", size: "25", id: "currentTeamImg") %>
      <label id="currentTeamName">ARI</label>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
    <% @teams.each do |t| %>
      <button class="dropdown-item small" type="button" onclick="setFavTeam('<%= t %>', '<%= image_path(t + '.png') %>')">
        <%= image_tag("#{t}.png", size: "16") %>
        <%= t %>
      </button>
    <% end %>
    </div>
  </div>

  <%= form.hidden_field(:favTeam, value: "ARI") %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

PoolFootballApp/app/views/poolers/edit.html.erb
<h1>Editing Pooler</h1>

<%= render 'form', pooler: @pooler %>

<%= link_to 'Retour', @pooler %>

PoolFootballApp/app/views/poolers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poolers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Favteam</th>
      <th>Pool</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poolers.each do |pooler| %>
      <tr>
        <td><%= pooler.name %></td>
        <td><%= pooler.favTeam %></td>
        <td><%= pooler.pool_id %></td>
        <td><%= pooler.user_id %></td>
        <td><%= link_to 'Show', pooler %></td>
        <td><%= link_to 'Edit', edit_pooler_path(pooler) %></td>
        <td><%= link_to 'Destroy', pooler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pooler', new_pooler_path %>

PoolFootballApp/app/views/poolers/new.html.erb
<h1>New Pooler</h1>

<%= render 'form', pooler: @pooler %>

PoolFootballApp/app/views/poolers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pooler.name %>
</p>

<p>
  <strong>Favteam:</strong>
  <%= @pooler.favTeam %>
</p>

<p>
  <strong>Pool:</strong>
  <%= @pool.name %>
</p>

<%= link_to 'Edit', edit_pooler_path(@pooler) %>