PoolFootballApp/config/routes.rb
Rails.application.routes.draw do
  # For now we disable the resources routes, to be re-activated for admin side
  # resources :users
  # resources :picks
  # resources :poolers
  # resources :pools
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Sessions base routes to login and logout
  get '/' => 'sessions#login'
  get '/sessions/goodbye' => 'sessions#goodbye'

  # Auth results routing
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get 'auth/failure' => '/'

  # Client facing resources
  resources :pools, only: [:index]
  resources :poolers, only: [:index, :new, :create, :show, :edit, :update]

  get '/picks' => 'picks#index'

  get '/picks/new/:season/:week' => 'picks#new', as: :new_pick_path
  post '/picks' => 'picks#create'

  get '/picks/:id' => 'picks#show', as: :pick
  get '/picks/search/:season/:week' => 'picks#show_week', as: :search_pick
end

PoolFootballApp/app/models/pick.rb
require 'json'

class Pick
  include Mongoid::Document
  field :season, type: Integer
  field :week, type: Integer
  field :pickstring, type: String

  belongs_to :pooler

  def json_picks?
    return pickstring[0] == "{"
  end

  def parse_picks
    if (json_picks?)
      # Handle json object
      JSON.parse(pickstring)
    else
      # Handle string split
      pickstring.split("|")
    end
  end
end

PoolFootballApp/app/controllers/picks_controller.rb
require 'json'

# Controller related for all operations to be done on picks data
class PicksController < ApplicationController
  before_action :set_pick, only: [:show, :edit, :update, :destroy]

  # GET /picks
  # GET /picks.json
  def index
    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end

    pooler = Pooler.where(user_id: user.id).first
    @max_season = (Pick.all.max_by do |x|
      x.season
    end)
    @max_season = !@max_season.nil? ? @max_season.season : Date.today.year

    data = Pick.where(pooler_id: pooler._id, season: @max_season).order_by(week: 1).to_a
    @picks = []

    (0..21).each do |i|
      @picks[i] = data.detect { |p| p.week == i + 1 }
    end
  end

  # GET /picks/1
  # GET /picks/1.json
  def show
    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end

    @pooler_name = Pooler.where(user_id: user.id).first.name

    picks = @pick.parse_picks
    @picks_data = get_week(@pick.season.to_s, @pick.week.to_s)['events'].each_with_index.map do |game, i|
      {
        game: {
          away_code: get_shortname(game['strAwayTeam']),
          home_code: get_shortname(game['strHomeTeam'])
        },
        pick: picks.is_a?(Hash) ? picks[game['idEvent']] : picks[i]
      }
    end
  end

  # GET /picks/2020/1
  def show_week
    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end

    pool = Pooler.where(user_id: user.id).first.pool
    @poolers_data = pool.poolers.map do |pooler|
      p = Pick.where(season: params[:season], week: params[:week], pooler_id: pooler.id).first
      {
        pooler_name: pooler.name,
        picks: !p.nil? ? p.parse_picks : nil
      }
    end

    @picks_data = get_week(params[:season], params[:week])['events'].each_with_index.map do |game, i|
      {
        game: game['strEventAlternate'],
        picks: @poolers_data.map do |p|
          if !p[:picks].nil?
            p[:picks].is_a?(Hash) ? p[:picks][game['idEvent']] : p[:picks][i]
          end
        end
      }
    end
  end

  # GET /picks/2020
  def show_season
    # add logic to show the picks in a better way
    # maybe get the picks for all poolers in pool
    @pick = Pick.where(season: params[:season]).first
  end

  # GET /picks/new
  def new
    @pick = Pick.new
    @pick.season = params[:season]
    @pick.week = params[:week]

    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end
    pooler = Pooler.where(user_id: user.id).first
    @favTeam = pooler.favTeam

    @week_data = get_week(params[:season], params[:week])['events'].map do |x|
      x[:home_code] = get_shortname(x['strHomeTeam'])
      x[:away_code] = get_shortname(x['strAwayTeam'])
      x
    end
  end

  # GET /picks/1/edit
  def edit
    puts '[Picks][Edit]'
  end

  # POST /picks
  # POST /picks.json
  def create
    @pick = Pick.new
    params = pick_params['pick']

    @pick.season = params['season']
    @pick.week = params['week']

    user = User.where(token: session[:user_token]).first
    if user.nil?
      redirect_to '/'
      return
    end

    pooler = Pooler.where(user_id: user.id).first
    @pick.pooler_id = pooler._id

    # Set the pick string here based on data
    @pick.pickstring = params['data'].to_json

    respond_to do |format|
      if @pick.save
        # Redirect properly with season, week params
        format.html { redirect_to @pick, notice: 'Pick was successfully created.' }
        format.json { render :show, status: :created, location: @pick }
      else
        format.html { render :new }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picks/1
  # PATCH/PUT /picks/1.json
  def update
    respond_to do |format|
      if @pick.update(pick_params)
        format.html { redirect_to @pick, notice: 'Pick was successfully updated.' }
        format.json { render :show, status: :ok, location: @pick }
      else
        format.html { render :edit }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1
  # DELETE /picks/1.json
  def destroy
    @pick.destroy
    respond_to do |format|
      format.html { redirect_to picks_url, notice: 'Pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pick
    @pick = Pick.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pick_params
    # params.require(:pick).permit(:season, :week, :pickstring, :pooler_id, :data)
    params
  end
end

PoolFootballApp/app/helpers/picks_helper.rb
module PicksHelper
end

PoolFootballApp/app/views/picks/_form.html.erb
<%= form_with(model: pick, local: true) do |form| %>
  <% if pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pick.errors.count, "error") %> prohibited this pick from being saved:</h2>

      <ul>
        <% pick.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row justify-content-center">
  <table class="w-50 table table-sm">
  <% @week_data.each do |game| %>
    <tr>
      <td style="text-align: right">
        <label for="<%= "pick_#{game['idEvent']}_#{game[:away_code]}" %>">
          <%= game["strAwayTeam"] %>
          <%= image_tag("#{game[:away_code]}.png", size: "21") %>
        </label>
      </td>
      <td>
        <input
          type="radio"
          name="<%= "pick[data][#{game['idEvent']}]" %>"
          id="<%= "pick_#{game['idEvent']}_#{game[:away_code]}" %>"
          value="<%= game[:away_code] %>"
          <% if(game[:home_code] == @favTeam) then %>
            <%= disabled="disabled" %>
          <% end %>
          <% if(game[:away_code] == @favTeam) then %>
            <%= checked="checked" %>
          <% end %>
        />
      </td>
      <td>
        VS.
      </td>
      <td>
        <input
          type="radio"
          name="<%= "pick[data][#{game['idEvent']}]" %>"
          id="<%= "pick_#{game['idEvent']}_#{game[:home_code]}" %>"
          value="<%= game[:home_code] %>"
          <% if(game[:away_code] == @favTeam) then %>
            <%= disabled="disabled" %>
          <% end %>
          <% if(game[:home_code] == @favTeam) then %>
            <%= checked="checked" %>
          <% end %>
        />
      </td>
      <td style="text-align: left">
        <label for="<%= "pick_#{game['idEvent']}_#{game[:home_code]}" %>">
          <%= image_tag("#{game[:home_code]}.png", size: "21") %>
          <%= game["strHomeTeam"] %>
        </label>
      </td>
    </tr>
  <% end %>
  </table>
  </div>

  <%= form.hidden_field(:season) %>
  <%= form.hidden_field(:week) %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

PoolFootballApp/app/views/picks/edit.html.erb
<h1>Editing Pick</h1>

<%= render 'form', pick: @pick %>

<%= link_to 'Voir', @pick %> |
<%= link_to 'Retour', picks_path %>

PoolFootballApp/app/views/picks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Picks - Saison <%= @max_season %></h1>
<h5>Choisir une semaine ...</h5>

<div class="btn-group" role="group">
  <% @picks.each_with_index do |pick, i| %>
    <% if (pick != nil) then %>
      <a href="<%= url_for pick %>"
        class="btn btn-outline-secondary btn-lg"
        role="button">
          <%= get_week_name(i+1) %>
      </a>
    <% else %>
      <a href="<%= url_for new_pick_path_url(:season=> @max_season, :week=> i+1) %>"
        class="btn btn-primary btn-lg"
        role="button">
          <%= get_week_name(i+1) %>
      </a>
    <% end %>
  <% end %>
</div>

PoolFootballApp/app/views/picks/new.html.erb
<h1>New Pick</h1>

<%= render 'form', pick: @pick %>

<%= link_to 'Retour', picks_path %>

PoolFootballApp/app/views/picks/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Choix pour saison <%= @pick.season %> - <%= get_week_long_name(@pick.week) %></h2>
<h4>Par <%= @pooler_name %></h4>

<table class="w-50 table table-sm table-bordered">
  <% @picks_data.each do |e| %>
    <tr>
      <td><%= e[:game][:away_code] %> VS. <%= e[:game][:home_code] %></td>
      <% if (e[:pick] != nil) then %>
        <td style="text-align: center"><%= image_tag("#{e[:pick]}.png", size: "21") %></td>
      <% else %>
        <td style="text-align: center"><%= e[:pick] %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= link_to 'Retour', picks_path %> | 
<%= link_to 'Choix du pool', search_pick_url(:season=> @pick.season, :week=> @pick.week)%>

PoolFootballApp/app/views/picks/show_week.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-sm table-bordered">
  <tr>
    <th>Game</th>
    <% @poolers_data.each do |pooler| %>
      <th><%= pooler[:pooler_name] %></th>
    <% end %>
  </tr>

  <% @picks_data.each do |p| %>
  <tr>
    <td><%= p[:game] %></td>
    <% p[:picks].each do |t| %>
      <% if (t != nil) then %>
        <td style="text-align: center"><%= image_tag("#{t}.png", size: "21") %></td>
      <% else %>
        <td style="text-align: center"><%= t %></td>
      <% end %>
    <% end %>
  </tr>
  <% end %>
</table>

<%= link_to 'Retour', picks_path %>